name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: Pull Docker image
        run: sudo docker pull angeltg1/api-pipeline-v2:latest
      - name: Delete Old docker container 
        run: sudo docker rm -f api-pipeline-v2-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 3000:3000 --name api-pipeline-v2-container angeltg1/api-pipeline-v2    

      